###
GET http://localhost:8080/comments

###
GET http://localhost:8080/comments/0

###
POST http://localhost:8080/comments
Content-Type: application/json

{
 "name": "read12"

}

###
DELETE http://localhost:8080/comments/1

###
#  PATCH  http://localhost:8080/comments/1
# Content-Type: application/json

# {
# "name":""

# }